# Generated by Django 2.2.24 on 2023-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0003_auto_20230501_2029'),
        ('users', '0003_auto_20230501_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
