# Generated by Django 2.2.24 on 2023-05-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialaccount',
            table='financial_account',
        ),
    ]
