# Generated by Django 2.2.24 on 2023-05-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0002_auto_20230501_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'managed': False},
        ),
    ]
