# Generated by Django 2.2.24 on 2023-05-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_purchase', models.CharField(max_length=100)),
                ('date_purchase', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('value_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_installments', models.IntegerField()),
                ('current_payment_installments', models.IntegerField()),
                ('type_purchase', models.CharField(max_length=100)),
                ('purchase_category', models.CharField(max_length=100)),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
